swagger: '2.0'
info:
  version: 'first version'
  title: Lambda Laboratory Server
  
paths:
  /screenshot:
    get:
      responses:
        200:
          description: Success
          schema:
            type: file

  /screenshot-weather:
    get:
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/CommonResponse"